version: '2'
services:
  bind:
    restart: always
    image: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind/:/etc/bind9/
      - ./bind/clefs/:/etc/bind9/clefs/:rw
      - ./bind/named.conf:/etc/bind9/named.conf:ro
      - ./bind/rndc.key:/etc/bind9/rndc.key
      - ./named/:/var/named/:rw
      - ./named/x.yyy.zzz.in-addr.arpa:/var/named/x.yyy.zzz.in-addr.arpa
      - ./named/d.cc.bbb.aa.in-addr.arpa:/var/named/d.cc.bbb.aa.in-addr.arpa
      - ./named/exemple.org:/var/named/exemple.org:rw
      - /var/log/named.log:/var/log/named.log
